export const AUTH_IS_CONNECTED = 'AUTH_IS_CONNECTED'
export const AUTH_IS_AUTHENTICATED = 'AUTH_IS_AUTHENTICATED'
export const AUTH_SIGNED_TERMS = 'AUTH_SIGNED_TERMS'
export const AUTH_PROFILE_NAME = 'AUTH_PROFILE_NAME'
